"""add password_reset_token column

Revision ID: ccdb632b8757
Revises: ca8f2e0f0fe2
Create Date: 2026-07-04 14:20:59.439656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccdb632b8757'
down_revision: Union[str, Sequence[str], None] = 'ca8f2e0f0fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('occasion', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('documents', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('product_images', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'image_document_id')
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_sessions_refresh_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'password_reset_token')
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=False)
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.add_column('products', sa.Column('image_document_id', sa.VARCHAR(length=36), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.alter_column('product_images', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_table('payment_methods')
    op.drop_table('collections')
    op.drop_table('brands')
    # ### end Alembic commands ###
