"""add status timestamp columns

Revision ID: de9c218e7bdf
Revises: f6a17e2923ab
Create Date: 2026-07-05 18:13:20.051483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9c218e7bdf'
down_revision: Union[str, Sequence[str], None] = 'f6a17e2923ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('packed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('on_delivery_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('on_delivery_at')
        batch_op.drop_column('packed_at')
        batch_op.drop_column('accepted_at')

    # ### end Alembic commands ###
