"""sync models to db

Revision ID: f28f951eaca3
Revises: ca8f2e0f0fe2
Create Date: 2026-07-05 17:40:35.207012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28f951eaca3'
down_revision: Union[str, Sequence[str], None] = 'ca8f2e0f0fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('label',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reject_reason', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('refund_description', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('refund_proof_images', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('refund_payment_proof', sa.String(length=500), nullable=True))
        batch_op.alter_column('shipping_address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('billing_address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('pending', 'accepted', 'rejected', 'packed', 'on_delivery', 'delivered', 'cancelled', 'refund_requested', 'refund_out_for_pickup', 'item_retrieved_from_customer', 'item_retrieved_by_admin', 'refund_on_the_way', 'refund_successful', 'refunded', name='order_status'),
               existing_nullable=False)
        batch_op.alter_column('payment_mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('shipping_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('tax',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('discount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_refresh_token_hash'))
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_refresh_token_hash'), ['refresh_token_hash'], unique=False)

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('tax',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('shipping_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('payment_mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'accepted', 'rejected', 'packed', 'on_delivery', 'delivered', 'cancelled', 'refund_requested', 'refund_out_for_pickup', 'item_retrieved_from_customer', 'item_retrieved_by_admin', 'refund_on_the_way', 'refund_successful', 'refunded', name='order_status'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.alter_column('billing_address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('shipping_address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('refund_payment_proof')
        batch_op.drop_column('refund_proof_images')
        batch_op.drop_column('refund_description')
        batch_op.drop_column('reject_reason')
        batch_op.drop_column('delivered_at')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('label',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
