"""add type and order_id to notification

Revision ID: 0eabdd916d8f
Revises: de9c218e7bdf
Create Date: 2026-07-05 18:23:32.816712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eabdd916d8f'
down_revision: Union[str, Sequence[str], None] = 'de9c218e7bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notification_order_id', 'orders', ['order_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notification_order_id', type_='foreignkey')
        batch_op.drop_column('order_id')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
